### PR TITLE
Fix some file opening issues + format code

### PR DESCRIPTION
**Pull request by No767**

### CODE REVIEW

**Comment by rjt-rockx** [comment]
It is thold instead of threshold, the whispercpp python bindings follow an API that's loosely similar to https://docs.rs/whisper-rs/ with a few modifications.

**Comment by rjt-rockx** [comment]
Also, looking through the file opening changes
The reason I wrote it that way was to clear the file contents before writing to it
That could probably be replaced with a line to remove the existing file before creating it

**Comment by rjt-rockx** [comment]
Thanks!

**Comment by No767** [comment]
np !

**Pull request merged**
